// 光谱刻度：两端必须是「真·反义/对立」的一对概念，且中间存在连续过渡地带。
// 编写原则：
//   1. 两端不能是「有/没有」这种二值判断（没有中间地带就没得猜）
//   2. 必须是人人有共识的尺度（避免「艺术/无聊」这种主观到无法讨论的）
//   3. 好的光谱应该让人争论 —— 比如「冰箱里剩的算不算干净」

export interface Spectrum {
  left: string
  right: string
}

export const SPECTRA: Spectrum[] = [
  { left: '冷漠', right: '热情' },
  { left: '安静', right: '吵闹' },
  { left: '便宜', right: '昂贵' },
  { left: '简单', right: '复杂' },
  { left: '无聊', right: '有趣' },
  { left: '缓慢', right: '飞快' },
  { left: '柔软', right: '坚硬' },
  { left: '冰冷', right: '滚烫' },
  { left: '轻盈', right: '沉重' },
  { left: '狭小', right: '宽敞' },
  { left: '崭新', right: '破旧' },
  { left: '保守', right: '冒险' },
  { left: '理性', right: '感性' },
  { left: '懒惰', right: '勤奋' },
  { left: '胆小', right: '勇敢' },
  { left: '邋遢', right: '整洁' },
  { left: '抠门', right: '挥霍' },
  { left: '粗心', right: '细致' },
  { left: '内向', right: '外向' },
  { left: '严肃', right: '幽默' },
  { left: '稚嫩', right: '成熟' },
  { left: '贫穷', right: '富有' },
  { left: '短暂', right: '漫长' },
  { left: '容易', right: '困难' },
  { left: '安全', right: '危险' },
  { left: '熟悉', right: '陌生' },
  { left: '普通', right: '稀有' },
  { left: '清淡', right: '重口' },
  { left: '健康', right: '垃圾食品' },
  { left: '家常', right: '米其林' },
  { left: '解渴', right: '越喝越渴' },
  { left: '填饱肚子', right: '发胖' },
  { left: '路边摊', right: '高档餐厅' },
  { left: '难吃', right: '好吃' },
  { left: '早餐', right: '宵夜' },
  { left: '自己做饭', right: '点外卖' },
  { left: '素', right: '荤' },
  { left: '微辣', right: '变态辣' },
  { left: '冰镇', right: '热饮' },
  { left: '工人', right: '老板' },
  { left: '实习', right: '退休' },
  { left: '加班', right: '摸鱼' },
  { left: '打工人', right: '自由职业' },
  { left: '朝九晚五', right: '007' },
  { left: '开卷考', right: '闭卷考' },
  { left: '及格', right: '满分' },
  { left: '小学', right: '博士' },
  { left: '学渣', right: '学霸' },
  { left: '补考', right: '保研' },
  { left: '文科', right: '理科' },
  { left: '初恋', right: '老夫老妻' },
  { left: '单身', right: '已婚' },
  { left: '相亲', right: '自由恋爱' },
  { left: '暗恋', right: '明恋' },
  { left: '分手', right: '复合' },
  { left: '网恋', right: '现实' },
  { left: '异地', right: '同城' },
  { left: '朋友', right: '恋人' },
  { left: '熟人', right: '陌生人' },
  { left: '社恐', right: '社牛' },
  { left: '独处', right: '聚会' },
  { left: '宅家', right: '出门' },
  { left: '躺平', right: '内卷' },
  { left: '佛系', right: '较真' },
  { left: '早起', right: '熬夜' },
  { left: '工作日', right: '周末' },
  { left: '下雨', right: '暴晒' },
  { left: '寒冬', right: '酷暑' },
  { left: '春天', right: '秋天' },
  { left: '城市', right: '乡村' },
  { left: '市中心', right: '郊区' },
  { left: '地铁', right: '自驾' },
  { left: '徒步', right: '坐车' },
  { left: '穷游', right: '奢华游' },
  { left: '说走就走', right: '计划半年' },
  { left: '猫', right: '狗' },
  { left: '甜粽', right: '咸粽' },
  { left: '豆腐脑甜的', right: '咸的' },
  { left: '番茄炒蛋加糖', right: '不加糖' },
  { left: '香菜好吃', right: '香菜是毒药' },
  { left: '五仁月饼', right: '蛋黄莲蓉' },
  { left: '咖啡', right: '茶' },
  { left: '可口可乐', right: '百事可乐' },
  { left: 'iOS', right: '安卓' },
  { left: '有线耳机', right: '无线耳机' },
  { left: '电子书', right: '纸质书' },
  { left: '电影', right: '电视剧' },
  { left: '追剧', right: '追综艺' },
  { left: '流行乐', right: '古典乐' },
  { left: '看展', right: '逛商场' },
  { left: '麻将', right: '剧本杀' },
  { left: '单机', right: '联机' },
  { left: '手游', right: '主机游戏' },
  { left: '健身房', right: '家里躺' },
  { left: '跑步', right: '游泳' },
  { left: '爬山', right: '海边' },
  { left: '儿童', right: '成人' },
  { left: '文科生', right: '理科生' },
  { left: '南方', right: '北方' },
  { left: '春节', right: '圣诞' },
  { left: '小时候', right: '现在' },
  { left: '现实', right: '理想' },
  { left: '运气', right: '实力' },
  { left: '过程', right: '结果' },
  { left: '省钱', right: '省时间' },
  { left: '实用', right: '好看' },
  { left: '质量', right: '数量' },
]
